export const inventario = [
  {
    id: "1",
    equipo: "Prensa hormigón 200 tf",
    etiqueta: "00001",
    nºserie: "45245-hk",
    tipo: "Prensas",
    estado: "Operativo",
    marca: "Inmaq",
    nºserie: "2003k-jj",
    peso: "375 kg",
    nbultos: "2",
    costeadecuacion: "523",
    valorestimado: "12500",
    Reservadoa: "Granada",
    Almacen: "Inmaq",
    imageninicial: "1",
    imagenfinal: "1",
  },
  {
    id: "2",
    equipo: "Empuje Barandillas",
    etiqueta: "00002",
    nºserie: "45245-hk",
    tipo: "Prensas",
    estado: "Operativo",
    marca: "Inmaq",
    nºserie: "2003k-jj",
    peso: "375 kg",
    nbultos: "2",
    costeadecuacion: "523",
    valorestimado: "12500",
    Reservadoa: "Sevilla",
    Almacen: "Inmaq",
    imageninicial: "2",
    imagenfinal: "2",
  },
  {
    id: "3",
    equipo: "Placa de carga",
    etiqueta: "00003",
    nºserie: "452sdf45-hk",
    tipo: "Prensas",
    estado: "Operativo",
    marca: "Inmaq",
    nºserie: "2003k-jj",
    peso: "375 kg",
    nbultos: "2",
    costeadecuacion: "523",
    valorestimado: "12500",
    Reservadoa: "Sevilla",
    Almacen: "Inmaq",
    imageninicial: "3",
    imagenfinal: "3",
  },
  {
    id: "4",
    equipo: "Prensa Marshall 5tf",
    etiqueta: "00004",
    nºserie: "f45-hk",
    tipo: "Prensas",
    estado: "Operativo",
    marca: "Inmaq",
    nºserie: "2003k-jj",
    peso: "375 kg",
    nbultos: "2",
    costeadecuacion: "523",
    valorestimado: "12500",
    Reservadoa: "Getafe",
    Almacen: "Inmaq",
    imageninicial: "4",
    imagenfinal: "4",
  },
  {
    id: "5",
    equipo: "Prensa Fenix",
    etiqueta: "00005",
    nºserie: "asdfdf45-hk",
    tipo: "Prensas",
    estado: "Operativo",
    marca: "Inmaq",
    nºserie: "2003k-jj",
    peso: "375 kg",
    nbultos: "2",
    costeadecuacion: "523",
    valorestimado: "12500",
    Reservadoa: "Valladolid",
    Almacen: "Inmaq",
    imageninicial: "0",
    imagenfinal: "0",
  },
  {
    id: "6",
    equipo: "Desgaste los Ángeles",
    etiqueta: "00006",
    nºserie: "452sdf45-hk",
    tipo: "Prensas",
    estado: "Operativo",
    marca: "Inmaq",
    nºserie: "2003k-jj",
    peso: "375 kg",
    nbultos: "2",
    costeadecuacion: "523",
    valorestimado: "12500",
    Reservadoa: "Granada",
    Almacen: "Inmaq",
    imageninicial: "0",
    imagenfinal: "0",
  },
  {
    id: "7",
    equipo: "Desgaste los Ángeles",
    etiqueta: "00007",
    nºserie: "452ss-hk",
    tipo: "Prensas",
    estado: "Operativo",
    marca: "Inmaq",
    nºserie: "2003k-jj",
    peso: "375 kg",
    nbultos: "2",
    costeadecuacion: "523",
    valorestimado: "12500",
    Reservadoa: "",
    Almacen: "Granada",
    imageninicial: "0",
    imagenfinal: "0",
  },
  {
    id: "8",
    equipo: "Prensa aceros ",
    etiqueta: "00008",
    nºserie: "445-hk",
    tipo: "Prensas",
    estado: "Operativo",
    marca: "Inmaq",
    nºserie: "2003k-jj",
    peso: "375 kg",
    nbultos: "2",
    costeadecuacion: "523",
    valorestimado: "12500",
    Reservadoa: "",
    Almacen: "Granada",
    imageninicial: "0",
    imagenfinal: "0",
  },
  {
    id: "9",
    equipo: "Prensa Multiensayo 200 kN",
    etiqueta: "00009",
    nºserie: "Inmaq ñlk5-hk",
    tipo: "Prensas",
    estado: "Operativo",
    marca: "Inmaq",
    nºserie: "2003k-jj",
    peso: "375 kg",
    nbultos: "2",
    costeadecuacion: "523",
    valorestimado: "12500",
    Reservadoa: "",
    Almacen: "Sevilla",
    imageninicial: "1",
    imagenfinal: "1",
  },
  {
    id: "10",
    equipo: "Prensa multiensayo 200 kN",
    etiqueta: "00010",
    nºserie: "2sdf45-hk",
    tipo: "Prensas",
    estado: "Operativo",
    marca: "Inmaq",
    nºserie: "2003k-jj",
    peso: "375 kg",
    nbultos: "2",
    costeadecuacion: "523",
    valorestimado: "12500",
    Reservadoa: "",
    Almacen: "Inmaq",
    imageninicial: "2",
    imagenfinal: "2",
  },
];


import * as communs from "./communs";

export const fetchInventarios = async (setState) => {
  communs.fetchData("inventarios", setState);
};

export const addInventario = async (newInventario) => {
  communs.addData("inventarios", newInventario);
};

export const updateInventario = async (inventarioId, updatedData) => {
  communs.updateData("inventarios",inventarioId,updatedData)
};

export const deleteInventario = async (inventarioId) => {
  communs.deleteData("inventarios",inventarioId)
};